local telescope_builtin = require('telescope.builtin')
vim.keymap.set('n', '<leader>ff', telescope_builtin.find_files, { desc = '[f]ind [f]iles' })
vim.keymap.set('n', '<leader>gf', telescope_builtin.git_files, { desc = 'find [g]it [f]iles' })
vim.keymap.set('n', '<leader>ps', function()
    telescope_builtin.grep_string({ search = vim.fn.input("Grep > ") })
end, { desc = '[p]roject [s]earch, (Grep in project base dir)' })
